---
title: "Course support"
---

Most of you will need help at some point and we want to make sure you can identify when that is without getting too frustrated and feel comfortable seeking help.

## Lectures and labs

If you have a question during lecture or lab, feel free to ask it! There are likely other students with the same question, so by asking you will create a learning opportunity for everyone.

## Office hours

You are encouraged to attend office hours during the times posted on the home page to ask questions about the course content and assignments. A lot of questions are most effectively answered in person, so office hours are a valuable resource. I encourage every one of you to take advantage of this resource! Pledge to stop by during office hours at least once during the first few days of class. If you truly have no questions to ask, just stop by and say hi and introduce yourself. You can find a [list of your professor's office hours here](/course-instructor.html).

#### Professor Email

If you are not available during office hours times or have a questions later in the evening or other times outside of class, email your professor at [tgeorge\@cornellcollege.edu](mailto:tgeorge@cornellcollege.edu). If your question involves code - it is very likely you will need to meet with him to get help. Please reach out with any concerns you have during the course!

## Academic support

### **Quantitative Reasoning Studio (QRS)**

There are times you may need help outside of class or office hours. Or, maybe you need something explained differently. In those instances, I encourage you to visit the **Quantitative Reasoning Studio** in Cole Library room 322. The [Quantitative Reasoning Studio (QRS)](https://www.cornellcollege.edu/library/ctl/qr/) offers free tutoring to all students at Cornell College. There will be at least 1 peer tutor who has taken this course and will be able to help you if you arrive at a time they are working. Feel free to email Jessica Johanningmeier at [QRS\@cornellcollege.edu](mailto:QRS@cornellcollege.edu "QRS@cornellcollege.edu") to ask when the tutor for this class will be available. They often will have a schedule posted on the wall in the studio.

### QRS Hours

| Day(s)          | Times                                |
|-----------------|--------------------------------------|
| Monday-Thursday | 8 a.m. - 5 p.m. and 7 p.m. - 10 p.m. |
| Friday          | 8 a.m. - 5 p.m.                      |
| Sunday          | 3 p.m. - 5 p.m. and 7 p.m. - 10 p.m. |

### Dungy Writing Studio

For help with your writing, visit the [Dungy Writing Studio](https://www.cornellcollege.edu/library/ctl/writing-studio/writing-studio-staff.shtml). You can make online appointments individually or in groups to get help with items such as your group project. If you have any questions about the studio, email Dungy Writing Studio Director and Director of Fellowships and Scholarships, Laura Farmer, at [lfarmer\@cornellcollege.edu](mailto:lfarmer@cornellcollege.edu).

### Writing Studio Hours

| Day(s)          | Times                                |
|-----------------|--------------------------------------|
| Monday-Thursday | 8 a.m. - 5 p.m. and 7 p.m. - 10 p.m. |
| Friday          | 8 a.m. - 5 p.m.                      |
| Sunday          | 1 p.m. - 5 p.m.                      |

### Academic Support Services

There are a variety of support services offered to all students. See more information at: <https://www.cornellcollege.edu/academics/support-services/index.shtml>\>

## Ebersole Health and Wellbeing Center

The mission of Cornell College Student Health Services complements the mission of the college by promoting the optimal well-being of students. We do this by:

-   providing and coordinating quality health care services
-   advocating for students in their pursuit of health and wellness
-   preparing students to be their own health advocates and informed consumers of appropriate health care services
-   providing health education to promote the development of healthy lifestyles

The Student Health Center is located in the Ebersole Building, directly south of the Thomas Commons. Appointments are preferred. You can schedule an appointment online or by phone at 319-895-4292. Walk-ins will be accommodated as time permits. Appointments with the nurse are free.

## Technology Support

If you have issues with your computer during the block, IT may be able to help. [Please submit a ticket](https://www.cornellcollege.edu/information-technology/).

## **Course materials costs**

There are no costs associated with this course. All readings will come from freely available, open resources (open-source textbooks, journal articles, etc.).
