---
title: 'Chapter 2 - Likelihoods'
subtitle: 'Does having boys or girls run in the family? '
editor: visual
---

## Questions

#### Model 1 – Sex Unconditional Model.  Each child is independent of the others, and there is a constant probability ( ) that a child is a boy.

1. Consider a small example with 3 families with compositions of children given by BBG, GBG, and GG.  
Find the maximum likelihood estimator (MLE) for   by:
a)	Conducting a numerical search in R for the largest likelihood over a fine grid of values 0-1.

b)	Conducting a numerical search in R for the largest log-likelihood between 0 and 1.
Illustrate the process graphically, and report the maximum value of the likelihood and log-likelihood functions.  Does it make sense that both methods would agree (and agree with the mathematical approach)?


2. Apply Model 1 to the NLSY data (families in Table 2 with 3 or fewer children).  Find the MLE for   by adapting the R code for (1).


#### Model 2 – Sex Conditional Model.  The probability of having a boy depends on whether you’ve had boys previously, so Model 2 will have three parameters:

 = probability of a boy when previously have had an equal number of boys and girls (neutral)
 
 = probability of a boy when previously have had more boys than girls (boy bias)
 
 = probability of a boy when previously have had more girls than boys (girl bias)

3. Write out the likelihood function given Model 2 for the small set of data in (1).  [You could also try BGG, GGB, BBB just for fun.]
