{
  "hash": "836f9d831a3bcb9af6bcf222467bc3e0",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Multilevel Models\"\nsubtitle: \"BMLR Chapter 8\"\nformat: \n  revealjs:\n    output-file: \"08_multilevel_mod_ch8.html\"\n    slide-number: true\n  html:\n    output-file: \"08_multilevel_mod_ch8_o.html\"\nlogo: \"../img/favicon.png\"\ncategories: [\"⚠️ Warning: Page Under Revision\"]\n---\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(GGally)\nlibrary(knitr)\nlibrary(patchwork)\nlibrary(viridis)\nlibrary(ggfortify)\nlibrary(kableExtra)\nlibrary(lme4)\nlibrary(broom.mixed)\n```\n:::\n\n\n## Learning goals (1/2) {.smaller}\n\n- Recognize a potential for correlation in a data set\n- Identify observational units at varying levels \n- Understand issues correlated data may cause in modeling\n- Understand how random effects models can be used to take correlation into account \n- Use EDA for multilevel data\n- Conduct univariate and bivariate EDA for multilevel models \n\n## Learning goals (2/2) {.smaller}\n\n- Write multilevel model , including assumptions about variance components, in by-level and composite forms\n- Interpret the model parameters, fixed effects, and variance components\n- Fit and interpret multilevel models \n- Compare maximum likelihood (ML) and restricted maximum likelihood (REML) estimation approaches\n- Understand general process for fitting and comparing multilevel models\n\n# Multilevel Models\n\n## Multilevel data {.smaller}\n\n- We can think of correlated data as a multilevel structure\n\n  - Population elements are aggregated into groups\n  - There are observational units and measurements at each level\n  \n. . .\n\n- For now we will focus on data with two levels: \n\n  - **Level one**: Most basic level of observation \n  - **Level two**: Groups formed from aggregated level-one observations \n\n\n\n## Two types of effects {.smaller}\n\n- **Fixed effects**: Effects that are of interest in the study\n  - Can think of these as effects whose interpretations would be included in a write up of the study\n\n. . .\n\n- **Random effects**: Effects we're not interested in studying but whose variability we want to understand \n  - Can think of these as effects whose interpretations would not necessarily be included in a write up of the study  \n\n\n\n## Practice Questions {.smaller}\n\nRadon is a carcinogen – a naturally occurring radioactive gas whose decay products are also radioactive – known to cause lung cancer in high concentrations. The EPA sampled more than 80,000 homes across the U.S.  Each house came from a randomly selected county and measurements were made on each level of each home.  Uranium measurements at the county level were included to improve the radon estimates.\n\n1. What is the most basic level of observation (Level One)? \n2. What are the group units (Level Two, Level Three, etc...)\n2. What is the response variable?\n3. Describe the within-group variation. \n4. What are the fixed effects? What are the random effects?\n\n::: aside\nEx. 1 from Section 7.10.1 in BMLR\n:::\n \n# Multilevel models\n\n## Data: Music performance anxiety {.smaller}\n\nThe data [`musicdata.csv`](data/musicdata.csv) come from the Sadler and Miller (2010) study of the emotional state of musicians before performances. The dataset contains information collected from 37 undergraduate music majors who completed the Positive Affect Negative Affect Schedule (PANAS), an instrument produces a measure of anxiety (negative affect) and a measure of happiness (positive affect). This analysis will focus on negative affect as a measure of performance anxiety.\n\nThe primary variables we'll use are\n\n- **`na`**: negative affect score on PANAS (the response variable)\n- **`perform_type`**: type of performance (Solo, Large Ensemble, Small Ensemble)\n- **`instrument`**: type of intstrument (Voice, Orchestral, Piano)\n\n## Look at data {.smaller}\n\n:::{.panel-tabset}\n\n### Data View\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n| id| diary|perform_type   | na|gender |instrument |\n|--:|-----:|:--------------|--:|:------|:----------|\n|  1|     1|Solo           | 11|Female |voice      |\n|  1|     2|Large Ensemble | 19|Female |voice      |\n|  1|     3|Large Ensemble | 14|Female |voice      |\n| 43|     1|Solo           | 19|Female |voice      |\n| 43|     2|Solo           | 13|Female |voice      |\n| 43|     3|Small Ensemble | 19|Female |voice      |\n\n\n:::\n:::\n\n\n### Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmusic <- read_csv(\"data/musicdata.csv\")\nmusic %>%\n  filter(id %in% c(1, 43)) %>%\n  group_by(id) %>%\n  slice(1:3) %>%\n  select(id, diary, perform_type, na, gender, instrument) %>%\n  kable()\n```\n:::\n\n\n:::\n\n- What are the Level One observations? Level Two observations? \n\n- What are the Level One variables? Level Two variables?\n\n\n\n## Univariate exploratory data analysis {.smaller}\n\n**Level One variables** \n\nTwo ways to approach univariate EDA (visualizations and summary statistics) for Level One variables: \n\n- Use individual observations (i.e., treat observations as independent)\n\n- Use aggregated values for each Level Two observation \n\n. . .\n\n**Level Two variables** \n\n- Use a data set that contains one row per Level Two observation \n\n. . .\n\nLet's do some Univariate EDA together\n\n\n## Unviariate EDA {.smaller}\n\n:::{.panel-tabset}\n\n### Plots\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](08_multilevel_mod_ch8_files/figure-revealjs/unnamed-chunk-4-1.png){width=960}\n:::\n:::\n\n\n### Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- ggplot(data = music, aes(x = na)) + \n  geom_histogram(fill = \"steelblue\", color = \"black\", binwidth = 2) + \n  labs(x = \"Individual negative affect\", \n       title = \"Negative affect scores\")\n\np2 <- music %>%\n  group_by(id) %>%\n  summarise(mean_na = mean(na)) %>%\n  ggplot(aes(x = mean_na)) + \n  geom_histogram(fill = \"steelblue\", color = \"black\", binwidth = 2) + \n  labs(x = \"Mean negative affect\", \n       title = \"Mean negative affect scores\")\n\np1 + p2\n```\n:::\n\n\n:::\n\n\n## Bivariate exploratory data analysis {.smaller}\n\n**Goals**\n\n- Explore general association between the predictor and response variable \n- Explore whether subjects at a given level of the predictor tend to have similar mean responses \n- Explore whether variation in response differs at different levels of a predictor\n\n. . .\n\nThere are two ways to visualize these associations: \n\n- One plot of individual observations (i.e., treat observations as independent)\n\n- Separate plots of responses vs. predictor for each Level Two observation (lattice plots)\n\n. . .\n\n**Now lets do some Bivariate EDA.**\n\n# Fitting the model \n\n## Questions we want to answer {.smaller}\n\nThe goal is to understand variability in performance anxiety (`na`) based on performance-level and musician-level characteristics. Specifically: \n\n- What is the association between performance type (large ensemble or not) and performance anxiety? Does the association differ based on instrument type (orchestral or not)?  \n\n. . .\n\n**What is the problem with using the following model to draw conclusions?**\n\n:::{.panel-tabset}\n\n### Model Output\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term                     | estimate| std.error| statistic| p.value|\n|:------------------------|--------:|---------:|---------:|-------:|\n|(Intercept)              |   15.721|     0.359|    43.778|   0.000|\n|orchestra                |    1.789|     0.552|     3.243|   0.001|\n|large_ensemble           |   -0.277|     0.791|    -0.350|   0.727|\n|orchestra:large_ensemble |   -1.709|     1.062|    -1.609|   0.108|\n\n\n:::\n:::\n\n\n### Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmusic <- music %>%\n  mutate(orchestra = if_else(instrument == \"orchestral instrument\", 1, 0), \n         large_ensemble = if_else(perform_type == \"Large Ensemble\", 1,0))\n\nols <- lm(na ~ orchestra + large_ensemble + orchestra * large_ensemble, \n          data = music)\ntidy(ols) %>% kable(digits = 3)\n```\n:::\n\n\n:::\n\n\n## Other modeling approaches {.smaller}\n\n1️⃣  Condense each musician's set of responses into a single outcome (e.g., mean max, last observation, etc.) and fit a linear model on these condensed observations \n\n- Leaves few observations (37) to fit the model\n- Ignoring a lot of information in the multiple observations for each musician\n\n. . .\n\n2️⃣ Fit a separate model for each musician understand the association between performance type (Level One models). Then fit a system of Level Two models to predict the fitted coefficients in the Level One model for each subject based on instrument type (Level Two model).\n\n. . .\n\n**Let's look at approach #2**\n\n\n\n## Two-level model {.smaller}\n\nWe'll start with the Level One model to understand the association between performance type and performance anxiety for the $i^{th}$ musician. \n\n\n$$na_{ij} = a_i + b_i ~ LargeEnsemble_{ij} + \\epsilon_i, \\hspace{5mm} \\epsilon_{ij} \\sim N(0,\\sigma^2)$$\n\n. . .\n\nWhy is it more meaningful to use performance type for the Level One model than instrument? \n\n. . .\n\nFor now, estimate $a_i$ and $b_i$ using least-squares regression.\n\n\n\n## Example Level One model {.smaller}\n\nBelow is partial data for observation #22\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmusic %>%\n  filter(id == 22) %>%\n  select(id, diary, perform_type, instrument, na) %>%\n  slice(1:3, 13:15) %>%\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n| id| diary|perform_type   |instrument            | na|\n|--:|-----:|:--------------|:---------------------|--:|\n| 22|     1|Solo           |orchestral instrument | 24|\n| 22|     2|Large Ensemble |orchestral instrument | 21|\n| 22|     3|Large Ensemble |orchestral instrument | 14|\n| 22|    13|Large Ensemble |orchestral instrument | 12|\n| 22|    14|Large Ensemble |orchestral instrument | 19|\n| 22|    15|Solo           |orchestral instrument | 25|\n\n\n:::\n:::\n\n\n\n\n## Level One model {.smaller}\n\n:::{.panel-tabset}\n\n### Model\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term           | estimate| std.error| statistic| p.value|\n|:--------------|--------:|---------:|---------:|-------:|\n|(Intercept)    |   24.500|      1.96|    12.503|   0.000|\n|large_ensemble |   -7.833|      2.53|    -3.097|   0.009|\n\n\n:::\n:::\n\n\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nmusic %>%\n  filter(id == 22) %>%\n  lm(na ~ large_ensemble, data = .) %>%\n  tidy() %>%\n  kable(digits = 3)\n```\n:::\n\n\n\n. . .\n\n**Repeat for all 37 musicians**\n\n### Slopes and Intercepts\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Recreated from BMLR Figure 8.9](08_multilevel_mod_ch8_files/figure-revealjs/unnamed-chunk-12-1.png){width=960}\n:::\n:::\n\n\n. . .\n\n**Now let's consider if there is an association between the estimated slopes, estimated intercepts, and the type of instrument**\n\n:::\n\n\n## Level Two Model {.smaller}\n\nThe slope and intercept for the $i^{th}$ musician can be modeled as\n\n$$\\begin{aligned}&a_i = \\alpha_0 + \\alpha_1 ~ Orchestra_i + u_i \\\\\n&b_i = \\beta_0 + \\beta_1 ~ Orchestra_i + v_i\\end{aligned}$$\n\n. . .\n\nNote the response variable in the Level Two models are not observed outcomes but the (fitted) slope and intercept from each musician\n\n. . .\n\n**Let's fit a level 2 model**\n\n\n\n## Estimated coefficients by instrument {.smaller}\n\n:::{.panel-tabset}\n\n\n### Output\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](08_multilevel_mod_ch8_files/figure-revealjs/unnamed-chunk-13-1.png){width=960}\n:::\n:::\n\n\n### Code\n\n::: {.cell}\n\n```{.r .cell-code}\nmusicians <- music %>%\n  distinct(id, orchestra) %>%\n  bind_cols(model_stats)\n\np1 <- ggplot(data = musicians, aes(x = intercepts, y = factor(orchestra))) + \n  geom_boxplot(fill = \"steelblue\", color = \"black\") + \n  labs(x = \"Fitted intercepts\", \n       y = \"Orchestra\")\n\np2 <- ggplot(data = musicians, aes(x = slopes, y = factor(orchestra))) + \n  geom_boxplot(fill = \"steelblue\", color = \"black\") + \n  labs(x = \"Fitted slopes\", \n       y = \"Orchestra\")\n\np1 / p2\n```\n:::\n\n\n:::\n\n\n## Level Two model {.smaller}\n\n:::{.panel-tabset}\n\n### Models\n\n**Model for intercepts**\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |   16.283|     0.671|    24.249|   0.000|\n|orchestra   |    1.411|     0.991|     1.424|   0.163|\n\n\n:::\n:::\n\n\n**Model for slopes**\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |   -0.771|     0.851|    -0.906|   0.373|\n|orchestra   |   -1.406|     1.203|    -1.168|   0.253|\n\n\n:::\n:::\n\n\n\n### Code \n\n**Model for intercepts**\n\n\n::: {.cell}\n\n```{.r .cell-code}\na <- lm(intercepts ~ orchestra, data = musicians) \ntidy(a) %>%\n  kable(digits = 3)\n```\n:::\n\n\n**Model for slopes**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nb <- lm(slopes ~ orchestra, data = musicians) \ntidy(b) %>%\n  kable(digits = 3)\n```\n:::\n\n\n\n:::\n\n## Writing out the models {.smaller}\n\n**Level One** \n\n$$\\hat{na}_{ij}  = \\hat{a}_i + \\hat{b}_i ~ LargeEnsemble_{ij}$$\n\nfor each musician. \n\n**Level Two** \n\n$$\\begin{aligned}&\\hat{a}_i = 16.283 + 1.441 ~ Orchestra_i \\\\\n&\\hat{b}_i = -0.771 - 1.406 ~ Orchestra_i\\end{aligned}$$\n\n\n\n## Composite model {.smaller}\n\n$$\\begin{aligned}\\hat{na}_i &= 16.283 + 1.441 ~ Orchestra_i - 0.771 ~ LargeEnsemble_{ij} \\\\\n&- 1.406 ~ Orchestra:LargeEnsemble_{ij}\\end{aligned}$$\n\n. . .\n\n(Note that we also have the error terms $\\epsilon_{ij}, u_i, v_i$ that we will discuss soon)\n\n- What is the predicted average performance anxiety before solos and small ensemble performances for vocalists and keyboardists? For those who place orchestral instruments? \n\n- What is the predicted average performance anxiety before large ensemble performances for those who play orchestral instruments?\n\n\n## Disadvantages to this approach {.smaller}\n\n⚠️ Weighs each musician the same regardless of number of diary entries\n\n⚠️  Drops subjects who have missing values for slope (7 individuals who didn't play a large ensemble performance) \n\n⚠️  Does not share strength effectively across individuals \n\n. . .\n\n\n**We will use a unified approach that utilizes likelihood-based methods to address some of these drawbacks.**\n\n\n\n## Questions\n\n1. How many Level One models are fit? \n2. How many Level Two models are fit?\n\n\n# Unified approach to two-level modeling\n\n## Framework {.smaller}\n\nLet $Y_{ij}$ be the performance anxiety for the $i^{th}$ musician before performance $j$. \n\n**Level One**\n\n$$Y_{ij} = a_i + b_i ~ LargeEnsemble + \\epsilon_{ij}$$\n\n. . .\n\n**Level Two**\n\n$$\\begin{aligned}&a_i = \\alpha_0 + \\alpha_1 ~ Orchestra_i+ u_i\\\\\n&b_i = \\beta_0 + \\beta_1~Orchestra_i + v_i\\end{aligned}$$\n\n. . .\n\nThis approach uses likelihood-based methods (instead of least squares) to address the previously mentioned disadvantages\n\n\n## Creating a Composite Model {.sortofsmall}\n\nPlug in the equations for $a_i$ and $b_i$ to get the **composite model** \n\n::::{.columns}\n\n:::{.column}\n\n$$Y_{ij} = a_i + b_i ~ LargeEnsemble + \\epsilon_{ij}$$\n\n:::\n\n:::{.column}\n\n$$\\begin{aligned}&a_i = \\alpha_0 + \\alpha_1 ~ Orchestra_i+ u_i\\\\\n&b_i = \\beta_0 + \\beta_1~Orchestra_i + v_i\\end{aligned}$$\n\n:::\n\n::::\n\n. . .\n\n$$\\begin{aligned}Y_{ij} &= a_i \\hspace{1.8in}+ \\hspace{1.62in} b_i ~ LargeEnsemble  \\hspace{2.2in}+ \\epsilon_{ij}\\\\\n&=\n(\\alpha_0 + \\alpha_1 ~ Orchestra_i+ u_i) + (\\beta_0 + \\beta_1~Orchestra_i + v_i)LargeEnsemble\\hspace{2.17in}+\\epsilon_{ij}\\\\\n&= \\space \\alpha_0 + \\alpha_1 ~ Orchestra_i+ u_i \\hspace{.2in} + \\beta_0LargeEnsemble+\\beta_1Orchestra_iLargeEnsemble+v_iLargeEnsemble+\\epsilon_{ij}\n\\end{aligned}$$\n\n## lmer Syntax {.smaller}\n\nlmer(response~fixed effect variables + (random effect variables|group variable),data = your_data)\n\n- we determine fixed and random effects based on our composite model\n- terms with Greek letters will be fixed effects\n- terms with random components, usually $u$, $v$, or $w$ will be random effects \n\n## Fitting our Model with lmer {.sortofsmall}\n\n$$\\begin{aligned} Y_{ij}&= \\space \\alpha_0 + \\alpha_1 ~ Orchestra_i+ u_i +\\space\\space\\space \\beta_0LargeEnsemble+\\beta_1Orchestra_iLargeEnsemble+v_iLargeEnsemble+\\epsilon_{ij}\\\\\n&=\\alpha_0 + \\alpha_1 ~ Orchestra_i + \\beta_0LargeEnsemble+\\beta_1Orchestra_iLargeEnsemble+u_i + v_iLargeEnsemble+\\epsilon_{ij}\n\\end{aligned}$$\n\n- All varibles with greek letters are fixed effects and all variables with $u$, $v$ are random effects. \n\n. . .\n\n\nlmer(na ~ 1 + Orchastra + LargeEnsemble + Orchestra * LargeEnsemble + (1+LargeEnsemble|id),data = music)\n\n\n\n## Composite model {.smaller}\n\nPlug in the equations for $a_i$ and $b_i$ to get the **composite model** \n\n\n$$\\begin{aligned}Y_{ij} &= (\\alpha_0 + \\alpha_1 ~ Orchestra_i + \\beta_0 ~ LargeEnsemble_{ij} \\\\ \n&+ \\beta_1 ~ Orchestra_i:LargeEnsemble_{ij})\\\\\n&+ (u_i + v_i ~ LargeEnsemble_{ij} + \\epsilon_{ij})\\end{aligned}$$\n\n\n- The **fixed effects** to estimate are $\\alpha_0, \\alpha_1, \\beta_0, \\beta_1$\n- The **error terms** are $u_i, v_i, \\epsilon_{ij}$\n\n. . .\n\nNote that we no longer need to estimate $a_i$ and $b_i$ directly as we did earlier. They conceptually connect the Level One and Level Two models. \n\n\n## Notation {.smaller}\n\n- Greek letters denote the fixed effect model parameters to be estimated\n  - e.g., $\\alpha_0, \\alpha_1, \\beta_0, \\beta_1$\n  \n- Roman letters denote the preliminary fixed effects at lower levels that will not be estimated directly. \n  - e.g. $a_i, b_i$\n\n- $\\sigma$ and $\\rho$ denote variance components that will be estimated \n\n- $\\epsilon_{ij}, u_i, v_i$ denote error terms \n\n\n\n\n## Error terms {.smaller}\n\n- We generally assume that the error terms are normally distributed, e.g. error associated with each performance of a given musician is $\\epsilon_{ij} \\sim N(0, \\sigma^2)$\n\n- For the Level Two models, the errors are \n  - $u_i$: deviation of musician $i$ from the mean performance anxiety before solos and small ensembles after accounting for the instrument \n  - $v_i$: deviance of musician $i$ from the mean difference in performance anxiety between large ensembles and other performance types after accounting for instrument\n\n- Need to account for fact that $u_i$ and $v_i$ are correlated for the $i^{th}$ musician \n\n\n## Intercept and Slope {.smaller}\n\n:::{.panel-tabset}\n\n### Plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Recreated from Figure 8.11](08_multilevel_mod_ch8_files/figure-revealjs/unnamed-chunk-19-1.png){width=960}\n:::\n:::\n\n\nQuestion: **Describe what we learn about the association between the slopes and intercepts based on this plot.** \n\n### Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmusicians %>%\n  filter(!is.na(slopes)) %>%\nggplot(aes(x = intercepts, y = slopes)) + \n  geom_point() + \n  geom_smooth(method = \"lm\") + \n  labs(x = \"Fitted intercepts\",\n       y = \"Fitted slopes\", \n       title = \"Fitted slopes and intercepts\", \n       subtitle = paste0(\"r = \", round(cor(musicians %>% filter(!is.na(slopes)) %>% pull(intercepts), musicians %>% filter(!is.na(slopes)) %>% pull(slopes)),3)))\n```\n:::\n\n\n:::\n\n\n\n\n\n\n\n## Distribution of Level Two errors {.smaller}\n\nUse a **multivariate normal** distribution for the Level Two error terms\n\n$$\\left[ \\begin{array}{c}\n            u_{i} \\\\ v_{i}\n          \\end{array}  \\right] \\sim N \\left( \\left[\n          \\begin{array}{c}\n            0 \\\\ 0\n          \\end{array} \\right], \\left[\n          \\begin{array}{cc}\n            \\sigma_{u}^{2} & \\rho_{uv}\\sigma_{u}\\sigma_v \\\\\n            \\rho_{uv}\\sigma_{u}\\sigma_v & \\sigma_{v}^{2}\n          \\end{array} \\right] \\right)$$\n          \nwhere $\\sigma^2_u$ and $\\sigma^2_v$ are the variance of $u_i$'s and $v_i$'s respectively, and $\\sigma_{uv}  = \\rho_{uv}\\sigma_u\\sigma_v$ is covariance between $u_i$ and $v_i$ \n\n- What does it mean for $\\rho_{uv} > 0$? \n- What does it mean for $\\rho_{uv} < 0$? \n\n- Being able to write out these mammoth variance-covariance matrices is less important than recognizing the number of variance components that must be estimated by our intended model.\n\n## Visualizing multivariate normal distribution {.smaller}\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Recreated from Figure 8.12](08_multilevel_mod_ch8_files/figure-revealjs/contour-boundary2-1.png){fig-align='center' width=60%}\n:::\n:::\n\n\n\n\n## Fit the model (1/2) {.smaller}\n\nFit multilevel model using the `lmer` function from the **lme4** package. Display results using hte `tidy()` function from the **broom.mixed** package. \n\n\n:::{.panel-tabset}\n\n### Model Output\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|effect   |group    |term                            | estimate| std.error| statistic|\n|:--------|:--------|:-------------------------------|--------:|---------:|---------:|\n|fixed    |NA       |(Intercept)                     |   15.930|     0.641|    24.833|\n|fixed    |NA       |orchestra                       |    1.693|     0.945|     1.791|\n|fixed    |NA       |large_ensemble                  |   -0.911|     0.845|    -1.077|\n|fixed    |NA       |orchestra:large_ensemble        |   -1.424|     1.099|    -1.295|\n|ran_pars |id       |sd__(Intercept)                 |    2.378|        NA|        NA|\n|ran_pars |id       |cor__(Intercept).large_ensemble |   -0.635|        NA|        NA|\n|ran_pars |id       |sd__large_ensemble              |    0.672|        NA|        NA|\n|ran_pars |Residual |sd__Observation                 |    4.670|        NA|        NA|\n\n\n:::\n:::\n\n\n\n### Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(lme4)\nlibrary(broom.mixed)\nmusic_model <- lmer(na ~ orchestra + large_ensemble + \n                      orchestra:large_ensemble + (large_ensemble|id), \n                    REML = TRUE, data = music)\n\ntidy(music_model) %>% kable(digits = 3)\n```\n:::\n\n\n:::\n\n\n\n## Fit the model in R (2/2) {.smaller}\n\n\n**na ~ orchestra + large_ensemble + orchestra:large_ensemble**: Represents the fixed effects + intercept \n\n. . .\n\n**(large_ensemble|id)**: Represents the error terms and associated variance components\n  - Specifies two error terms: $u_i$ corresponding to the intercepts, $v_i$ corresponding to effect of large ensemble\n  \n\n\n## Tidy output {.smaller}\n\nDisplay results using the `tidy` function from the **broom.mixed** package. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(broom.mixed)\ntidy(music_model) \n```\n:::\n\n\n- Get fixed effects only \n\n. . .\n\n**tidy(music_model) %>% filter(effect == \"fixed\")**\n\n- Get errors and variance components only\n\n. . .\n\n**tidy(music_model) %>% filter(effect == \"ran_pars\")**\n\n\n\n## Model output: Fixed effects {.smaller}\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|effect |group |term                     | estimate| std.error| statistic|\n|:------|:-----|:------------------------|--------:|---------:|---------:|\n|fixed  |NA    |(Intercept)              |   15.930|     0.641|    24.833|\n|fixed  |NA    |orchestra                |    1.693|     0.945|     1.791|\n|fixed  |NA    |large_ensemble           |   -0.911|     0.845|    -1.077|\n|fixed  |NA    |orchestra:large_ensemble |   -1.424|     1.099|    -1.295|\n\n\n:::\n:::\n\n\n\n. . .\n\n**Label the fixed effects**\n\n\n\n## Model output: Random effects {.smaller}\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|effect   |group    |term                            | estimate| std.error| statistic|\n|:--------|:--------|:-------------------------------|--------:|---------:|---------:|\n|ran_pars |id       |sd__(Intercept)                 |    2.378|        NA|        NA|\n|ran_pars |id       |cor__(Intercept).large_ensemble |   -0.635|        NA|        NA|\n|ran_pars |id       |sd__large_ensemble              |    0.672|        NA|        NA|\n|ran_pars |Residual |sd__Observation                 |    4.670|        NA|        NA|\n\n\n:::\n:::\n\n\n\n. . .\n\n**Label the error terms and variance components**\n\n\n\n## Interpret the effects  {.smaller}\n\n- Split into 3 groups. \n\n- Each group will write the interpretation for one main effect and one variance component. The terms on each slide do not necessarily have a direct correspondence to each other. \n\n- One person write the group's interpretations on the board. \n\n\n## Comparing fixed effects estimates {.smaller}\n\nBelow are the estimated coefficients and standard errors for four modeling approaches.\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: from BMLR Table 8.3\n\n|Variable   |Independence |Two.Stage   |LVCF        |Multilevel  |\n|:----------|:------------|:-----------|:-----------|:-----------|\n|Intercept  |15.72(0.36)  |16.28(0.67) |15.20(1.25) |15.93(0.64) |\n|Orch       |1.79(0.55)   |1.41(0.99)  |1.45(1.84)  |1.69(0.95)  |\n|Large      |-0.28(0.79)  |-0.77(0.85) |-           |-0.91(0.85) |\n|Orch*Large |-1.71(1.06)  |-1.41(1.20) |-           |-1.42(1.10) |\n\n\n:::\n:::\n\n\n\n## Questions\n\n- How do the coefficient estimates compare? \n- How do the standard errors compare? \n\n## Pseudo R-squared Values {.smaller}\n\n$$\\textrm{Pseudo }R^2_{L1} = \\frac{\\hat{\\sigma}^{2}(\\textrm{Model A})-\\hat{\\sigma}^{2}(\\textrm{Model B})}{\\hat{\\sigma}^{2}(\\textrm{Model A})}$$\n- Pseudo R-squared values are not universally reliable as measures of model performance. \n- Because of the complexity of estimating fixed effects and variance components at various levels of a multilevel model, it is not unusual to encounter situations in which covariates in a Level Two equation for, say, the intercept remain constant (while other aspects of the model change), yet the associated pseudo R-squared values differ or are negative. For this reason, pseudo R-squared values in multilevel models should be interpreted cautiously.\n\n\n# ML and REML\n\n## ML and REML {.smaller}\n\nMaximum Likelihood (ML) and Restricted (Residual) Maximum Likelihood (REML) are the two most common methods for estimating the fixed effects and variance components\n\n. . .\n\n**Maximum Likelihood (ML)** \n\n- Jointly estimate the fixed effects and variance components using all the <u>sample data</u>\n- Can be used to draw conclusions about fixed and random effects\n- *Issue*: Fixed effects are treated as known values when estimating variance components\n  - Results in biased estimates of variance components (especially when sample size is small)\n\n\n\n## ML and REML {.smaller}\n\n**Restricted Maximum Likelihood (REML)**\n\n- Estimate the variance components using the <u>sample residuals</u> not the sample data\n- It is conditional on the fixed effects, so it accounts for uncertainty in fixed effects estimates. This results in unbiased estimates of variance components.\n\n. . .\n\nExample using OLS\n\n::: aside\n[See the post [Maximum Likelihood (ML) vs. REML](https://towardsdatascience.com/maximum-likelihood-ml-vs-reml-78cf79bef2cf) for details and illustration of ML vs. REML.\n:::\n\n\n\n## ML or REML? {.smaller}\n\n- Research has not determined one method absolutely superior to the other\n\n- **REML** (`REML = TRUE`; default in `lmer`) is preferable when \n  - the number of parameters is large or primary, or \n  - primary objective is to obtain estimates of the model parameters \n\n- **ML** (`REML = FALSE`) <u>must</u> be used if you want to compare nested fixed effects models using a likelihood ratio test (e.g., a drop-in-deviance test).\n  - For REML, the goodness-of-fit and likelihood ratio tests can only be used to draw conclusions about variance components \n\n<br> \n\n::: aside\nSource: Singer, J. D. & Willett, J. B. (2003). *Applied longitudinal data analysis: Modeling change and event occurrence*. Oxford university press.\n:::\n\n\n## Comparing ML and REML {.smaller}\n\n\n::: {.cell}\n\n:::\n\n\n<style type=\"text/css\">\n.tg  {border-collapse:collapse;border-spacing:0;}\n.tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;\n  overflow:hidden;padding:10px 5px;word-break:normal;}\n.tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;\n  font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}\n.tg .tg-7bx6{border-color:inherit;font-family:Tahoma, Geneva, sans-serif !important;font-size:16px;text-align:left;\n  vertical-align:top}\n.tg .tg-k70d{border-color:inherit;font-family:Tahoma, Geneva, sans-serif !important;font-size:16px;font-weight:bold;\n  text-align:center;vertical-align:top}\n.tg .tg-sr1h{border-color:inherit;font-family:Tahoma, Geneva, sans-serif !important;font-size:16px;text-align:right;\n  vertical-align:top}\n</style>\n<table class=\"tg\">\n<thead>\n  <tr>\n    <th class=\"tg-7bx6\"></th>\n    <th class=\"tg-k70d\" colspan=\"2\">Maximum Likelihood</th>\n    <th class=\"tg-k70d\" colspan=\"2\">Restricted Maximum Likelihood</th>\n  </tr>\n</thead>\n<tbody>\n  <tr>\n    <td class=\"tg-k70d\">Term</td>\n    <td class=\"tg-k70d\">Estimate</td>\n    <td class=\"tg-k70d\">Std. Error</td>\n    <td class=\"tg-k70d\">Estimate</td>\n    <td class=\"tg-k70d\">Std. Error</td>\n  </tr>\n  <tr>\n    <td class=\"tg-7bx6\">(Intercept)</td>\n    <td class=\"tg-sr1h\">15.924</td>\n    <td class=\"tg-sr1h\">0.623</td>\n    <td class=\"tg-sr1h\">15.930</td>\n    <td class=\"tg-sr1h\">0.641</td>\n  </tr>\n  <tr>\n    <td class=\"tg-7bx6\">orchestra1</td>\n    <td class=\"tg-sr1h\">1.696</td>\n    <td class=\"tg-sr1h\">0.919</td>\n    <td class=\"tg-sr1h\">1.693</td>\n    <td class=\"tg-sr1h\">0.945</td>\n  </tr>\n  <tr>\n    <td class=\"tg-7bx6\">large_ensemble1</td>\n    <td class=\"tg-sr1h\">-0.895</td>\n    <td class=\"tg-sr1h\">0.827</td>\n    <td class=\"tg-sr1h\">-0.911</td>\n    <td class=\"tg-sr1h\">0.845</td>\n  </tr>\n  <tr>\n    <td class=\"tg-7bx6\">orchestra1:large_ensemble1</td>\n    <td class=\"tg-sr1h\">-1.438</td>\n    <td class=\"tg-sr1h\">1.074</td>\n    <td class=\"tg-sr1h\">-1.424</td>\n    <td class=\"tg-sr1h\">1.099</td>\n  </tr>\n  <tr>\n    <td class=\"tg-7bx6\">sd__(Intercept)</td>\n    <td class=\"tg-sr1h\">2.286</td>\n    <td class=\"tg-sr1h\">NA</td>\n    <td class=\"tg-sr1h\">2.378</td>\n    <td class=\"tg-sr1h\">NA</td>\n  </tr>\n  <tr>\n    <td class=\"tg-7bx6\">cor__(Intercept).large_ensemble1</td>\n    <td class=\"tg-sr1h\">-1.00</td>\n    <td class=\"tg-sr1h\">NA</td>\n    <td class=\"tg-sr1h\">-0.635</td>\n    <td class=\"tg-sr1h\">NA</td>\n  </tr>\n  <tr>\n    <td class=\"tg-7bx6\">sd__large_ensemble1</td>\n    <td class=\"tg-sr1h\">0.385</td>\n    <td class=\"tg-sr1h\">NA</td>\n    <td class=\"tg-sr1h\">0.672</td>\n    <td class=\"tg-sr1h\">NA</td>\n  </tr>\n  <tr>\n    <td class=\"tg-7bx6\">sd__Observation</td>\n    <td class=\"tg-sr1h\">4.665</td>\n    <td class=\"tg-sr1h\">NA</td>\n    <td class=\"tg-sr1h\">4.670</td>\n    <td class=\"tg-sr1h\">NA</td>\n  </tr>\n</tbody>\n</table>\n\n\n\n## Strategy for building multilevel models {.smaller}\n\n- Conduct exploratory data analysis for Level One and Level Two variables \n\n- Fit model with no covariates to assess variability at each level \n\n- Create Level One models. Start with a single term, then add terms as needed. \n\n- Create Level Two models. Start with a single term, then add terms as needed. Start with equation for intercept term. \n\n- Begin with the full set of variance components, then remove variance terms as needed. \n\n. . .\n\n*Alternate model building strategy in BMLR Section 8.6*\n\n. . .\n\nSee BMLR Sections 8.6 - 8.11 for full step-by-step analysis.\n\n\n## Acknowledgements {.smaller}\n\nThe content in the slides is from \n\n- [BMLR: Chapter 8 - Introduction to Multilevel Models](https://bookdown.org/roback/bookdown-BeyondMLR/ch-multilevelintro.html)\n  - Initial versions of the slides are by Dr. Maria Tackett, Duke University\n- Singer, J. D. & Willett, J. B. (2003). *Applied longitudinal data analysis: Modeling change and event occurrence*. Oxford university press.    \n- Sadler, Michael E., and Christopher J. Miller. 2010. “Performance Anxiety: A Longitudinal Study of the Roles of Personality and Experience in Musicians.” Social Psychological and Personality Science 1 (3): 280–87. http://dx.doi.org/10.1177/1948550610370492.\n- Initial versions of the slides are by Dr. Maria Tackett, Duke University\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}